### ISSUE TITLE
feat: validate Checkpoint config

### ISSUE THREAD

**Issue by perfectmak** [checkpoint-labs/checkpoint#11]
Currently, Checkpoint assumes that the config object passed into the constructor is properly structured, but this will not always be the case. 
Validation should be done on the config objects structure before starting the indexer. Maybe a using json schema validation.

**Comment by ef3n9r98** [comment]
Hey @perfectmak, I know some devs who'd be interested in working on this. Is there a budget for fixing this issue, and if so, how much? 

I'd put this issue up on [OpenQ]([www.openq.dev](http://www.openq.dev/)).

Thanks!
