### ISSUE TITLE
feat: move to Prisma

### ISSUE THREAD

**Issue by bonustrack** [checkpoint-labs/checkpoint#148]
Many of the changes will require an ORM to deal with, for example #10 or #61 require changing table or column on insert or update queries. Moving to Prisma should allow us to automate this, it would also abstract the logic for filters and others optimizations like 1-1 & 1-n queries. Prisma also support multiple database: MySQL, Postgres, MongoDB, this is something that was requested previously.

**Comment by bonustrack** [comment]
More context from @perfectmak https://getjamtech.notion.site/Using-Prisma-as-Checkpoints-Data-Layer-19de503a9ad1415ea262606448a03d46

**Comment by Sekhmet** [comment]
This won't be implemented due to Prisma limitations in our usecase.
