### ISSUE TITLE
feat: create a token API using Checkpoint

### ISSUE THREAD

**Issue by bonustrack** [checkpoint-labs/checkpoint#186]
We should create an API to retrieve token holding info for a single or multiple holders, the code should live in this repository: https://github.com/snapshot-labs/token-api-checkpoint the Checkpoint template can be used as starter (https://github.com/snapshot-labs/checkpoint-template). The API should use this format:

```gql
type AccountToken {
  id: String! # Equal to <tokenAddress>-<accountAddress>
  account: String
  token: Token
  balance: Float # Parsed balance based on token decimals
  rawBalance: BigInt # Raw balance without decimals 
  modified: Int # Last modified timestamp in seconds
  tx: String # Last transaction that modified balance
}

type Token {
  id: String! # Token address
  decimals: Int
  name: String
  symbol: String
  totalSupply: BigInt
}
```

This require Checkpoint version after `v0.1.0-beta.13` (currently master branch).

Here is some docs to learn more about Checkpoint: https://docs.checkpoint.fyi

**Comment by Sekhmet** [comment]
Transfer event tracking example: https://github.com/snapshot-labs/checkpoint-template/commit/f44073170238f64134483bf8339327f11bcba0fc

**Comment by bonustrack** [comment]
This issue is assigned to @HashRei

**Comment by bonustrack** [comment]
Hey @HashRei are you still looking on the issue or should we assign it to someone else?
