### ISSUE TITLE
feat: add subgraph health check entity by default

### ISSUE THREAD

**Issue by antiyro** [checkpoint-labs/checkpoint#204]
Add an health check entity by default for every subgraph, native to Checkpoint. Something like this should do the job :

```graphql
type Subgraph {
  id: ID! # default set to 1
  health: Bool # check if the subgraph is up/down
  lastBlockNumber: BigInt # last synced block number
  lastBlockHash: BigInt # last synced block hash
  synced: Bool # Network sync status
}

**Comment by bonustrack** [comment]
@antiyro We have the entity "metadata" that is already storing the current block number, we could add others information there. I think the sync is something we can check from the UI, we don't need it to be exposed by the API. And for health check how you imagine this to work?

**Comment by Villegas2003** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/checkpoint).

### My background and how it can be leveraged
I am a software developer and a student at Universidad Cenfotec. I have experience working with various technologies, including Angular for frontend development, Springboot for backend development, and MySQL for database management. Additionally, I have a strong interest in blockchain technology and have been eager to apply my knowledge in the Web3 space.

### How I plan on tackling this issue
Understanding the requirement:
First, I will analyze in detail the requirement to add a health check entity for each subgraph in Checkpoint, ensuring I fully understand the expected functionality.

Research and Planning:
I will research the current structure of the Checkpoint code and review any existing documentation on the implementation of subgraphs. Based on this, I will develop a detailed plan for implementing the new health check entity.

**Comment by bonustrack** [comment]
@Villegas2003 Thank you for your interest but I don't recommend doing this task, it's not relevant anymore,

**Comment by Villegas2003** [comment]
Hi @bonustrack,

Thank you for your response. I understand that the previous task is no longer relevant. Is there currently an active issue that I could help with? I would love to contribute and collaborate in any way that would be useful.

Best Regards
