### ISSUE TITLE
feat: Notification center

### ISSUE THREAD

**Issue by antiyro** [checkpoint-labs/checkpoint#208]
Integrate a notification center native to checkpoint following Argent/Ledger request.
Supporting Telegram, Mail and any IFTT module like here for Ledger fresh :
- https://github.com/LedgerHQ/notification-center

**Comment by Sekhmet** [comment]
This can be implemented at writer level, per-project as needed if I understand the request correctly.

Closing the issue as it doesn't seem something that belongs in Checkpoint's natively.
