### ISSUE TITLE
style: create dashboard UI

### ISSUE THREAD

**Issue by bonustrack** [checkpoint-labs/checkpoint#222]
Create design for a dashboard UI.

<img width="910" alt="image" src="https://user-images.githubusercontent.com/16245250/233777252-65e28c0a-40f6-449d-ada6-111cfb35f2d6.png">

The UI should include:

- Checkpoint logo on top left
- A progress bar to show how much an instance is sync with current and total block number
- An input to type the API address of the instance
- Social links
- A form to query data (similar than on https://hub.snapshot.org/graphql)
- A section with the results of the query

**Comment by DennohKim** [comment]
Hello guys, 

Can i be assigned this task?

**Comment by bonustrack** [comment]
@DennohKim Thank you but actually this is not relevant anymore we don't need it. Closing this issue.
