### ISSUE TITLE
bug: Query with nested where clause fails with "Cannot read properties of undefined (reading 'toLowerCase')"

### ISSUE THREAD

**Issue by solimander** [checkpoint-labs/checkpoint#258]
Queries with nested where clauses fail [here](https://github.com/checkpoint-labs/checkpoint/blob/e6dd8b3580604d39de79f4c8c41fb2103582677c/src/graphql/resolvers.ts#L74).

Looks like line 73 should be:

```typescript
const nestedReturnType = (
  returnType.getFields()[fieldName].type as GraphQLList<GraphQLObjectType>
).ofType;
````

I don't mind opening a PR for this, but want to double check this can be reproduced and isn't some misconfiguration on my end.

**Comment by bonustrack** [comment]
@solimander Can you share the schema and query that you are using to reproduce this issue?

**Comment by solimander** [comment]
Sure thing. Here's the [schema](https://github.com/Prop-House/prop-house-monorepo/blob/25cc8e1df04f4e769c26e7c4dd28876b28fd8813/packages/prop-house-checkpoint/src/schema.gql).

Query:

```gql
query {
  votes(where: { round_: { sourceChainRound: "round_address" }, proposal_: { proposalId: 1 } }) {
    id
  }
}
```
