### ISSUE TITLE
bug: sub-entity filter is not recognized

### ISSUE THREAD

**Issue by bonustrack** [checkpoint-labs/checkpoint#267]
Using this instance with checkpoint v0.1.0-beta.24 the filter for the Topic entity does not includes sub-entities, using sub-entities as filter return an error `Field "category" is not defined by type "Topic_filter".`, here is the queries I've tried:

http://localhost:3000/?query=query%20%7B%0A%20%20topics%20(where%3A%20%7B%20category_%3A%20%7B%20id%3A%200%20%7D%20%7D)%20%7B%0A%20%20%20%20id%0A%20%20%20%20category%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A

http://localhost:3000/?query=query%20%7B%0A%20%20topics%20(where%3A%20%7B%20category%3A%200%20%7D)%20%7B%0A%20%20%20%20id%0A%20%20%20%20category%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A

**Comment by Sekhmet** [comment]
Can you show indexer code and schema?

Similar query works there:
https://api-1.snapshotx.xyz/?query=%7B%0A%20%20proposals(where%3A%20%7Bspace_%3A%20%7Bid%3A%20%220x018e1a59a2ee1d0b1978638be45b9b0153ce7b7799a1c7424776f3dfb0439c86%22%7D%7D)%20%7B%0A%20%20%20%20id%0A%20%20%20%20space%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A
