### ISSUE TITLE
feat: add BigInt type with custom precision

### ISSUE THREAD

**Issue by Sekhmet** [checkpoint-labs/checkpoint#272]
BigInt is mapped to DB's native `bigint` type, which might be too small. Decimal types can have decimal point so they need to be exposed as strings in ORM.

We could add custom BigInt support that at DB level would be stored as DECIMAL(P, 0) and could be used as bigint on JS side.

**Comment by ktarun1419** [comment]
Is this issue still relevant?

**Comment by Sekhmet** [comment]
@ktarun1419 hey, I took a look at it and I don't think it makes sense to implement it as with existing [BigDecimal support](https://docs.checkpoint.fyi/guides/bigint-and-bigdecimal#custom-decimal-types) users can define type like `BiggerInt` and just set it to use `{ p: 40, d: 0 }` or whatever suits the usecase and they would get pretty much the same thing (except it will be represented as string instead of bigint on JS side), but I'm not sure it's worth extra complexity.
